branches:
  only:
  - myblog

language: node_js

sudo: false

node_js:
#- '5.4'
- '0.12'

before_install:
- openssl aes-256-cbc -K $encrypted_3db31b6eb68b_key -iv $encrypted_3db31b6eb68b_iv
  -in doc/github_travis.enc -out ~\/.ssh/github_travis -d
- chmod 600 ~/.ssh/github_travis

- eval $(ssh-agent)
- ssh-add ~/.ssh/github_travis
- cp doc/ssh_config ~/.ssh/config

- git config --global user.name "zhangmx"
- git config --global user.email icediv@163.com
- git clone -b master https://github.com/zhangmx/zhangmx.github.io.git .deploy_git

install:
- npm install hexo-cli -g
- npm install

script:
- hexo clean
- hexo g
- hexo d
