branches:
  only:
  - blog

language: node_js

sudo: false

node_js:
- '5.4'

before_install:
#- openssl aes-256-cbc -K $encrypted_26b4962af0e7_key -iv $encrypted_26b4962af0e7_iv
#  -in doc/travis.enc -out ~/.ssh/id_rsa -d
#- chmod 600 ~/.ssh/id_rsa

- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp doc/ssh_config ~/.ssh/config
- git config --global user.name "zhangmx"
- git config --global user.email icediv@163.com
- git clone -b master git@github.com:zhangmx/zhangmx.github.io.git .deploy_git

install:
- npm install hexo-cli -g
- npm install

script:
- hexo clean
- hexo g
- hexo d
